### ISSUE TITLE
homework review completed

### ISSUE THREAD

**Issue by hatelove** [kcwang-tw/TDD-DayTwo#1]
做得挺好的，對 LINQ 如果更熟悉，會把很多的 foreach 迴圈直接以更簡潔的 LINQ 取代掉。

最後的 production code 也挺乾淨的，用 index++ 我覺得很好，比起大家常用的 item count--; 來得漂亮一些。

**Comment by kcwang-tw** [comment]
感謝91的指導！LINQ語法的確是我現在還需要再加強的地方
